"use client";

import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import { CustomThemeProvider } from "@/components/ThemeProvider";
import {
  QueryCache,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={inter.className + " " + "dark:bg-main-black"}>
          <CustomThemeProvider attribute="class">
            <Theme>
              <Navbar />
              {children}
            </Theme>
          </CustomThemeProvider>
        </body>
      </QueryClientProvider>
    </html>
  );
}
